<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'templating.finder' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\templating\\TemplateNameParserInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\framework-bundle\\Templating\\TemplateFilenameParser.php';

@trigger_error('The "templating.finder" service is deprecated since Symfony 4.3 and will be removed in 5.0.', E_USER_DEPRECATED);

return $this->privates['templating.finder'] = new \Symfony\Bundle\FrameworkBundle\CacheWarmer\TemplateFinder(($this->services['kernel'] ?? $this->get('kernel', 1)), new \Symfony\Bundle\FrameworkBundle\Templating\TemplateFilenameParser(), ($this->targetDirs[3].'\\src/Resources'));
