<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.ZQ7_3oO' shared service.

return $this->privates['.service_locator.ZQ7_3oO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\DashboardController::Dashboard' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\HomePageController::HomePage' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\PermissionController::Permission' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\RoleController::Role' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\UsersController::Users' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\DashboardController:Dashboard' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\HomePageController:HomePage' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\PermissionController:Permission' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\RoleController:Role' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\UsersController:Users' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
], [
    'App\\Controller\\DashboardController::Dashboard' => '?',
    'App\\Controller\\HomePageController::HomePage' => '?',
    'App\\Controller\\PermissionController::Permission' => '?',
    'App\\Controller\\RoleController::Role' => '?',
    'App\\Controller\\UsersController::Users' => '?',
    'App\\Controller\\DashboardController:Dashboard' => '?',
    'App\\Controller\\HomePageController:HomePage' => '?',
    'App\\Controller\\PermissionController:Permission' => '?',
    'App\\Controller\\RoleController:Role' => '?',
    'App\\Controller\\UsersController:Users' => '?',
]);
