<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
<<<<<<<< HEAD:var/cache/dev/ContainerGppNAFq/get_ServiceLocator_I3qGmU2Service.php
// Returns the private '.service_locator.i3qGmU2' shared service.

return $this->privates['.service_locator.i3qGmU2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
========
// Returns the private '.service_locator.llTVoVD' shared service.

return $this->privates['.service_locator.llTVoVD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
>>>>>>>> 6b8312cafdd1e1e6507aef7f0b80f576dd3e4691:var/cache/dev/Container6sX3lFd/get_ServiceLocator_LlTVoVDService.php
    'App\\Controller\\DashboardController::Dashboard' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\HomePageController::HomePage' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\PermissionController::Permission' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\PermissionController::PermissionDelete' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\PermissionController::PermissionUpdate' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\RoleController::Role' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\StockController::Stock' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
<<<<<<<< HEAD:var/cache/dev/ContainerGppNAFq/get_ServiceLocator_I3qGmU2Service.php
========
    'App\\Controller\\UsersController::UserView' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
>>>>>>>> 6b8312cafdd1e1e6507aef7f0b80f576dd3e4691:var/cache/dev/Container6sX3lFd/get_ServiceLocator_LlTVoVDService.php
    'App\\Controller\\UsersController::Users' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\DashboardController:Dashboard' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\HomePageController:HomePage' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\PermissionController:Permission' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\PermissionController:PermissionDelete' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\PermissionController:PermissionUpdate' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\RoleController:Role' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\StockController:Stock' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
<<<<<<<< HEAD:var/cache/dev/ContainerGppNAFq/get_ServiceLocator_I3qGmU2Service.php
========
    'App\\Controller\\UsersController:UserView' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
>>>>>>>> 6b8312cafdd1e1e6507aef7f0b80f576dd3e4691:var/cache/dev/Container6sX3lFd/get_ServiceLocator_LlTVoVDService.php
    'App\\Controller\\UsersController:Users' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
], [
    'App\\Controller\\DashboardController::Dashboard' => '?',
    'App\\Controller\\HomePageController::HomePage' => '?',
    'App\\Controller\\PermissionController::Permission' => '?',
    'App\\Controller\\PermissionController::PermissionDelete' => '?',
    'App\\Controller\\PermissionController::PermissionUpdate' => '?',
    'App\\Controller\\RoleController::Role' => '?',
    'App\\Controller\\StockController::Stock' => '?',
<<<<<<<< HEAD:var/cache/dev/ContainerGppNAFq/get_ServiceLocator_I3qGmU2Service.php
========
    'App\\Controller\\UsersController::UserView' => '?',
>>>>>>>> 6b8312cafdd1e1e6507aef7f0b80f576dd3e4691:var/cache/dev/Container6sX3lFd/get_ServiceLocator_LlTVoVDService.php
    'App\\Controller\\UsersController::Users' => '?',
    'App\\Controller\\DashboardController:Dashboard' => '?',
    'App\\Controller\\HomePageController:HomePage' => '?',
    'App\\Controller\\PermissionController:Permission' => '?',
    'App\\Controller\\PermissionController:PermissionDelete' => '?',
    'App\\Controller\\PermissionController:PermissionUpdate' => '?',
    'App\\Controller\\RoleController:Role' => '?',
    'App\\Controller\\StockController:Stock' => '?',
<<<<<<<< HEAD:var/cache/dev/ContainerGppNAFq/get_ServiceLocator_I3qGmU2Service.php
========
    'App\\Controller\\UsersController:UserView' => '?',
>>>>>>>> 6b8312cafdd1e1e6507aef7f0b80f576dd3e4691:var/cache/dev/Container6sX3lFd/get_ServiceLocator_LlTVoVDService.php
    'App\\Controller\\UsersController:Users' => '?',
]);
