<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_user.user_provider.username_email' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\security-core\\User\\UserProviderInterface.php';
include_once $this->targetDirs[3].'\\vendor\\friendsofsymfony\\user-bundle\\Security\\UserProvider.php';
include_once $this->targetDirs[3].'\\vendor\\friendsofsymfony\\user-bundle\\Security\\EmailUserProvider.php';

return $this->privates['fos_user.user_provider.username_email'] = new \FOS\UserBundle\Security\EmailUserProvider(($this->services['fos_user.user_manager'] ?? $this->load('getFosUser_UserManagerService.php')));
