<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'templating.engine.php' shared service.

@trigger_error('The "templating.engine.php" service is deprecated since Symfony 4.3 and will be removed in 5.0.', E_USER_DEPRECATED);

$this->privates['templating.engine.php'] = $instance = new \Symfony\Bundle\FrameworkBundle\Templating\TimedPhpEngine(($this->privates['templating.name_parser'] ?? $this->load('getTemplating_NameParserService.php')), new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'templating.helper.actions' => ['privates', 'templating.helper.actions', 'getTemplating_Helper_ActionsService.php', true],
    'templating.helper.assets' => ['privates', 'templating.helper.assets', 'getTemplating_Helper_AssetsService.php', true],
    'templating.helper.code' => ['privates', 'templating.helper.code', 'getTemplating_Helper_CodeService.php', true],
    'templating.helper.form' => ['privates', 'templating.helper.form', 'getTemplating_Helper_FormService.php', true],
    'templating.helper.logout_url' => ['privates', 'templating.helper.logout_url', 'getTemplating_Helper_LogoutUrlService.php', true],
    'templating.helper.request' => ['privates', 'templating.helper.request', 'getTemplating_Helper_RequestService.php', true],
    'templating.helper.router' => ['privates', 'templating.helper.router', 'getTemplating_Helper_RouterService.php', true],
    'templating.helper.security' => ['privates', 'templating.helper.security', 'getTemplating_Helper_SecurityService.php', true],
    'templating.helper.session' => ['privates', 'templating.helper.session', 'getTemplating_Helper_SessionService.php', true],
    'templating.helper.slots' => ['privates', 'templating.helper.slots', 'getTemplating_Helper_SlotsService.php', true],
    'templating.helper.stopwatch' => ['privates', 'templating.helper.stopwatch', 'getTemplating_Helper_StopwatchService.php', true],
    'templating.helper.translator' => ['privates', 'templating.helper.translator', 'getTemplating_Helper_TranslatorService.php', true],
], [
    'templating.helper.actions' => '?',
    'templating.helper.assets' => '?',
    'templating.helper.code' => '?',
    'templating.helper.form' => '?',
    'templating.helper.logout_url' => '?',
    'templating.helper.request' => '?',
    'templating.helper.router' => '?',
    'templating.helper.security' => '?',
    'templating.helper.session' => '?',
    'templating.helper.slots' => '?',
    'templating.helper.stopwatch' => '?',
    'templating.helper.translator' => '?',
]), ($this->services['templating.loader'] ?? $this->load('getTemplating_LoaderService.php')), ($this->privates['debug.stopwatch'] ?? ($this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true))), $this->load('getTemplating_GlobalsService.php'));

$instance->setCharset('UTF-8');
$instance->setHelpers(['slots' => 'templating.helper.slots', 'request' => 'templating.helper.request', 'session' => 'templating.helper.session', 'router' => 'templating.helper.router', 'assets' => 'templating.helper.assets', 'actions' => 'templating.helper.actions', 'code' => 'templating.helper.code', 'translator' => 'templating.helper.translator', 'form' => 'templating.helper.form', 'stopwatch' => 'templating.helper.stopwatch', 'logout_url' => 'templating.helper.logout_url', 'security' => 'templating.helper.security']);

return $instance;
