<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFZZQWqR\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFZZQWqR/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFZZQWqR.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFZZQWqR\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerFZZQWqR\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'FZZQWqR',
    'container.build_id' => 'c7083aa8',
    'container.build_time' => 1684110436,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFZZQWqR');
